### ISSUE TITLE
Make post box and button pretty

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#105]

**Comment by mnijmeh11** [comment]
I might have gone a little overboard with css

**Comment by aseebart** [comment]
The text box is done but something weird happened with the button. Did we want it to look pretty?

**Comment by mnijmeh11** [comment]
I tried to add css to the site and it was not liked by the others....I will give you a style sheet that can be shared by all html documents...

**Comment by aseebart** [comment]
Duplicate of issue #112
