### ISSUE TITLE
Understand Python/Django Unit and Integration Testing

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#11]
Investigate which test frameworks are the best options to apply to our projects. I expect different answers will exist at two levels:
- A general python unit test framework, at the single function or single object level
- An HTTP API testing framework, at the whole system level

Both levels should be evaluated, and we should determine if a single framework could viably handle both options. Additionally, consider adding a database testing mechanism.
1. we want to make sure that at all levels we are getting proper data from server.

**Comment by mnijmeh11** [comment]
I might want to use deploy bot as a tester before deploying..
