### ISSUE TITLE
Implement look & feel

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#112]
We should decide on, and unambiguously define our site's target style.

**Comment by bencdelaney** [comment]
This will influence #105.

**Comment by mnijmeh11** [comment]
Ok

**Comment by aseebart** [comment]
What do you mean by style. I feel that the look of our site now is OK or are you talking about coding style?

**Comment by bencdelaney** [comment]
The look of our site is _OK_. I think that investing a little time in making it look _great_ could have a major impact on user impressions: people like shiny things.

**Comment by bencdelaney** [comment]
And we don't have to do all the work ourselves. There are a lot of ways to make a site look great without trying too hard. I'll see if I can post an idea or two shortly.

**Comment by bencdelaney** [comment]
This looks promising: http://getbootstrap.com/customize/

We could just write to standard Bootstrap styles for now, then can recompile and swap in new values whenever we want to.

**Comment by mnijmeh11** [comment]
Look and feel

-----Original Message-----

**Comment by aseebart** [comment]
looks good to me but I am not quite sure how it works. Maybe of we could take a meeting to look at this.

**Comment by mnijmeh11** [comment]
Tell me when

-----Original Message-----

**Comment by chaneberg** [comment]
@aseebart, is it OK if I assign this to me?
