### ISSUE TITLE
Create content for real event

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#114]

**Comment by mnijmeh11** [comment]
when are we going to get the description of the plays

**Comment by areinhardt14** [comment]
I just got the cast list; it's on our Google Drive folder now.

**Comment by chaneberg** [comment]
we will need to make 5 play lists:

<pre>all
wednesday
thursday
wednesday-chronological
thursday-chronological</pre>

**Comment by bencdelaney** [comment]
_Copied from #145, because it's probably more appropriate here_

A PostgreSQL-backed (I bailed on MSSQL) install is up at http://tttr-pre-prod.azurewebsites.net/. We can one-click-swap pre-prod and production, because pre-prod is a deployment slot in the same webapp.

It's currently pointed at a test database, but we should be able to export and import data very easily. If anyone feels like populating production data, we could create a fixture from the clean data (sans reviews, etc.) and use that to populate the real production database.

**Comment by bencdelaney** [comment]
@areinhardt14, could you let us know if Aliya has either of the two missing entries?

**Comment by chaneberg** [comment]
I just populated the database. I took the liberty of adding images for the two plays that didn't have them, "Tape" and "The Chocolate Affair". They are still missing descriptions.

**Comment by chaneberg** [comment]
By the way, I treated the play program as definitive where it didn't agree with the other information on Google Drive.

**Comment by mnijmeh11** [comment]
We tried our best to get them. I did but they didn't get it to us...

-----Original Message-----

**Comment by bencdelaney** [comment]
The last to plays are in the Google Doc! @aseebart, do you want to deal with those images?

**Comment by mnijmeh11** [comment]
I have no access to post them...

-----Original Message-----
