### ISSUE TITLE
Understand integration options for external library

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#12]
Determine how we should handle the integration of external open-source code, specifically https://github.com/vivekn/sentiment. Determine if we should run the app alongside our own, as a service we call, or incldue the code in our app.Investigate using a package manager (such as Pip), versus simply pulling the raw files.

**Comment by areinhardt14** [comment]
The best way I can see is to use their API: http://sentiment.vivekn.com/docs/api/
We can send a POST request with the text(s) to classify and receive a JSON response(s) back.

**Comment by mnijmeh11** [comment]
So I might want to use deploy it to help us test and deploy our database. 
Thanks
Moses 

-----Original Message-----
