### ISSUE TITLE
URL Rewrite

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#123]
On the server

**Comment by chaneberg** [comment]
The landing page doesn't use django templates, so it could be served statically is index.html instead of doing a URL rewrite. Just an idea.

**Comment by bencdelaney** [comment]
Hmm. We'd still end up with /statler/ (or whatever) on the front of everything else though, and it would limit our flexibility with the landing page.

**Comment by bencdelaney** [comment]
This probably isn't relevant anymore.
