### ISSUE TITLE
Deploy 0.4

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#127]
Get it working.

**Comment by chaneberg** [comment]
Do this to clone the repository:

<pre>git clone &lt;url&gt;
cd ...
git checkout origin/master</pre>

**Comment by chaneberg** [comment]
Don't forget to use `python manage.py createsuperuser` to create an admin site account.

**Comment by chaneberg** [comment]
I think I broke something by trying to re-clone the repository... sorry Anthony.

**Comment by mnijmeh11** [comment]
Unable to get ip and URL to point to tententenreviews.com... Sorry.... Maybe I can setup a different image on bitnami that will be able to get the job done right

**Comment by bencdelaney** [comment]
I've pushed the code we actually have in prod to the azure-beta-deployment branch. It's quite a mess, because I was in such a hurry, but I'll take a shot at cleaning it up next week.
