### ISSUE TITLE
Write document for theater students

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#130]

**Comment by mnijmeh11** [comment]
Aliya  whitehill awhitehill14@georgefox.edu will be getting ready to get some images and text about the future ten ten plays...give her a week...

**Comment by areinhardt14** [comment]
I put a draft in our Google Drive; if you want to make any changes to it (e.g. more/less information), then go ahead.

**Comment by mnijmeh11** [comment]
are we going to have enough time to get it up if they take a week to get the data to us....
