### ISSUE TITLE
Send email to theater class

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#140]
once the server is up, giving them a link to the site and the doc Anastasia wrote

**Comment by mnijmeh11** [comment]
Sent it and I am waiting for reply on play details

**Comment by bencdelaney** [comment]
Did you send an email to someone in theatre, @mnijmeh11? I believe this issue related to the beta launch information.

**Comment by mnijmeh11** [comment]
here is a discription from the school theater people.....

**Comment by mnijmeh11** [comment]
Dead Right
by Elaine Jarvik

A friend's tedious, grammatically incorrect obituary plunges Penny and Bill into a prickly discussion at the end of a work day. How will the world remember you? Should the world remember you? A touching comedy about discovering what is truly important in life.
![o-reading-newspaper-facebook 2](https://cloud.githubusercontent.com/assets/9537033/11454144/0f36e35e-95d8-11e5-99a7-d462be77c812.jpg)

**Comment by mnijmeh11** [comment]
I was for a while trying to get the show information to be displayed on the site 

-----Original Message-----
