### ISSUE TITLE
PDF Generation

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#146]
Determine how we want to handle this.

**Comment by chaneberg** [comment]
This is the document we will hand to the play directors, which is basically all our data in PDF form.

We decided to use Django templates to generate an HTML page with formatting. The HTML page will then be converted into a pdf.

See this link #155 for what has been done so far.

What needs to be done:
- add the usual HTML tags like doctype, html, head, utf-8 encoding, body
- style the page. Keep it simple but make the tables look better (column width should be set)
- find a program that converts HTML to PDFs

The HTML is at `statler_util/templates/directors-report.html`. The things in `{{ }}` will be replaced with text when the page is served.

Run a local server with `$ python manage.py runserver` to preview the page at `localhost:8000/util/directors-report`.

**Comment by chaneberg** [comment]
I moved the HTML to `statler_util/templates/directors-report.html` and the URL is now at `localhost:8000/util/directors-report`

**Comment by bencdelaney** [comment]
Do we have a plan for this, branch-wise? @chaneberg, do you want to move it, or leave it in charles and work in a different branch until it's merged?

**Comment by mnijmeh11** [comment]
I will try to get it done asap

**Comment by chaneberg** [comment]
@mnijmeh11 

There is a line of code that is commented out that you will need to uncomment in order to serve the page on localhost.

The line is `#url(r'^directors-report/$', views.getDirectorsReport, name='directors-report')` in the file `statler/statler_util/urls.py`.

Comment it back out when you are done.

**Comment by chaneberg** [comment]
@B3nD3lan3y If you review my pull request we can merge it

**Comment by mnijmeh11** [comment]
Will do

**Comment by mnijmeh11** [comment]
At doctor office. I will get to it asap

**Comment by chaneberg** [comment]
1. We're going to update your statler folder to the current dev branch. In a console, do these commands in order:
   <pre>git checkout -f origin/dev
   git checkout -b pdf-report
   git push -u origin pdf-report</pre>
2. do your work
3. when finished, use git to commit and push:
   <pre>git add -A
   git commit -m "some message"
   git push</pre>
4. open a pull request on GitHub

**Comment by chaneberg** [comment]
Chrome has a "print to PDF" option that should work for converting the pages to PDF.
