### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#148]
Do this once we stand up the beefier server.

**Comment by mnijmeh11** [comment]
it has been working for both old and new serve. old one had better results but the new one cn support our needs. response time between 281 ms to 2.99 seconds... with a lot of requests and repeated requests...13x  per event....overall the site got 10 on a lot fo the site ratings for overal functionality.....\

**Comment by mnijmeh11** [comment]
good. overall

**Comment by mnijmeh11** [comment]
done testing...from different location and broswer types and connection types....all was within desired usability....
