### ISSUE TITLE
Get program content to theatre

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#149]
- QR Code
- URL
- Mini descriptiony-pluggy-thing

**Comment by bencdelaney** [comment]
This has been emailed. I'll close it when we hear back.

**Comment by mnijmeh11** [comment]
here is one of the plays
Dead Right
by Elaine Jarvik

A friend's tedious, grammatically incorrect obituary plunges Penny and Bill into a prickly discussion at the end of a work day. How will the world remember you? Should the world remember you? A touching comedy about discovering what is truly important in life.
![o-reading-newspaper-facebook 2](https://cloud.githubusercontent.com/assets/9537033/11583440/bb457cb6-9a0e-11e5-97d3-bf2153a1922d.jpg)

**Comment by bencdelaney** [comment]
We're in!
