### ISSUE TITLE
Make tententenreviews.com resolve to azure server (not using a redirect)

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#154]
see https://azure.microsoft.com/en-us/documentation/articles/web-sites-custom-domain-name/

**Comment by bencdelaney** [comment]
Our Azure server is at [tttr.azurewebsites.net](tttr.azurewebsites.net)

The IP Address is 40.112.143.140, but just setting up that IP Address DNS record won't be sufficient. I think we need a CNAME record from tententenreviews.com to tttr.azurewebsites.net.

**Comment by mnijmeh11** [comment]
Done but I need panel access to. Do more

**Comment by bencdelaney** [comment]
_From Azure Portal:_
To point a custom domain name to your app, Microsoft Azure must verify that you are authorized to do so. First, create a CNAME resource record with your DNS provider that points from either www.yourdomain.com to tttr.azurewebsites.net, or from awverify.www.yourdomain.com to awverify.tttr.azurewebsites.net.

**Comment by mnijmeh11** [comment]
got done view couple otpions..... 1and1 and digitalocean

**Comment by bencdelaney** [comment]
[It looks like this is working!](http://tententenreviews.com)

**Comment by mnijmeh11** [comment]
It needed a little bit more work because it was serving it up as two sites in the DNS records.. Fixed...

-----Original Message-----
