### ISSUE TITLE
Create file to submit to Brent with links to project

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#167]

**Comment by mnijmeh11** [comment]
I emailed you a starter

**Comment by chaneberg** [comment]
Draft is on Google Drive.

**Comment by chaneberg** [comment]
Should we give Brent admin access so he can see the admin site, review ranking, and report generation?

**Comment by mnijmeh11** [comment]
Ben said no...

-----Original Message-----

**Comment by chaneberg** [comment]
Then should we give Brent admin access to the pre-prod deployment instead, since it doesn't have important data?

**Comment by bencdelaney** [comment]
Is there a compelling reason to give him admin access? Will he care? If we think the answer is yes, I don't think that giving him access to prod is the end of the world. I just wasn't sure that is was necessary.

**Comment by mnijmeh11** [comment]
I don't know if he will have time to go to it. It will not hurt but might help to give him read only access . It might by giving read only access show him our dedication to secure coding...
Do what you think is good..your the boss..

-----Original Message-----

**Comment by bencdelaney** [comment]
This has been turned in.
