### ISSUE TITLE
Images for the Wiki

### ISSUE THREAD

**Issue by aseebart** [GFUCABAM/statler#2]
![1](https://cloud.githubusercontent.com/assets/14076787/9950644/80c64fcc-5d71-11e5-9800-e6703f5afaab.jpg)

![2](https://cloud.githubusercontent.com/assets/14076787/9950648/90b94db2-5d71-11e5-9254-a7f46ed0203e.jpg)

![3](https://cloud.githubusercontent.com/assets/14076787/9950650/90bb0f58-5d71-11e5-97dd-96c73ef8411f.jpg)

![4](https://cloud.githubusercontent.com/assets/14076787/9950649/90b9f60e-5d71-11e5-8747-2cef2639f7a6.jpg)

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/10328309/ceb3426c-6c67-11e5-9c61-db65f686bffe.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12008786/10328312/ced1504a-6c67-11e5-80ec-b1583baeeaf6.PNG)
![capture3](https://cloud.githubusercontent.com/assets/12008786/10328313/ced32474-6c67-11e5-9a27-9a5e32da3cc4.PNG)
![capture4](https://cloud.githubusercontent.com/assets/12008786/10328311/ced0bbb2-6c67-11e5-9d08-11ef06c9249b.PNG)
![capture5](https://cloud.githubusercontent.com/assets/12008786/10328314/ced34666-6c67-11e5-9ac4-063579155436.PNG)
![landing page - done posting](https://cloud.githubusercontent.com/assets/12008786/10328316/ced5d49e-6c67-11e5-9d26-5fbf9a327ff3.png)
![landing page - post](https://cloud.githubusercontent.com/assets/12008786/10328310/cec67b20-6c67-11e5-823e-ec184827d7fb.png)
![landing page](https://cloud.githubusercontent.com/assets/12008786/10328315/ced59a4c-6c67-11e5-8345-840e3c3af14c.png)
![list of plays page](https://cloud.githubusercontent.com/assets/12008786/10328317/cee076b0-6c67-11e5-8e63-1f5d0807a429.png)
![play detail page](https://cloud.githubusercontent.com/assets/12008786/10328318/cee20598-6c67-11e5-92a3-4ea8d274d59b.png)

**Comment by chaneberg** [comment]
![capture2](https://cloud.githubusercontent.com/assets/12008786/10328343/11ec28aa-6c68-11e5-9e13-f1e8d431927f.PNG)
![capture4](https://cloud.githubusercontent.com/assets/12008786/10328344/12106fb2-6c68-11e5-93e3-9a4e99943700.PNG)

**Comment by chaneberg** [comment]
Images used in the Wiki are uploaded here, following advice from http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/11143817/fc573e5a-89ac-11e5-9c08-eb425cf36040.PNG)

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/11369425/a8002a2c-9273-11e5-9a84-564545785163.PNG)

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/11374380/a6e4c320-928a-11e5-8c18-b33f4b5043b5.PNG)

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/11584309/bed7a882-9a17-11e5-9fcb-7ce73e81b931.PNG)

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/11587012/7e4402de-9a2b-11e5-8db4-f816b35a2215.PNG)
