### ISSUE TITLE
Build 0.1 /api/plays/{url-title} endpoint

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#20]
With:
- title
- director

**Comment by bencdelaney** [comment]
Oops. Wrong issue :-P

**Comment by chaneberg** [comment]
<code>/api/play-list/</code> is built. Which isn't quite what this issue says, but it's the right idea.

**Comment by bencdelaney** [comment]
The right idea indeed. Looks great!

**Comment by mnijmeh11** [comment]
Closer to release day
