### ISSUE TITLE
pictures of the board

### ISSUE THREAD

**Issue by mnijmeh11** [GFUCABAM/statler#23]
So here is what we wrote about the server.
![wp_20151008_19_11_35_pro](https://cloud.githubusercontent.com/assets/9537033/10396443/54ab4fc2-6e57-11e5-9baf-4326b8714188.jpg)
![wp_20150924_19_17_50_pro](https://cloud.githubusercontent.com/assets/9537033/10396441/54a9d02a-6e57-11e5-9299-9cb92b2f0db0.jpg)
![wp_20150924_19_17_55_pro](https://cloud.githubusercontent.com/assets/9537033/10396442/54ab0044-6e57-11e5-9e6d-8272a60889ce.jpg)

**Comment by chaneberg** [comment]
![mod9](https://cloud.githubusercontent.com/assets/12008786/10838345/bef46bfe-7e81-11e5-8680-94b3593c0d07.png)

**Comment by chaneberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/12008786/11369180/87430b34-9272-11e5-8c53-03d2aef55df3.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12008786/11369181/875bb080-9272-11e5-9af1-9de65768a1e3.PNG)
