### ISSUE TITLE
Unit Test Plays table

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#26]
Make sure that things work. At least make sure we can save and retrieve plays, add other cases at will.

**Comment by areinhardt14** [comment]
I've written a couple of tests but am having issues trying to run them because the password authentication for user 'postgres' failed (from settings.py). How can I fix this? Or I could wait until the meeting if that's easier.

**Comment by bencdelaney** [comment]
The username and password are hardcoded in the "settings.py" file in the
base Statler directory. You can change them to match your local postgres
user.

**Comment by bencdelaney** [comment]
Originally merged in #70, and debugged in #60. Now working!
