### ISSUE TITLE
Get index.html into Django site server

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#27]
- Move the client code into statler_site
- Wire up the statler_site app to serve the page
- If we're feeling crazy, use URL templating to find the API.

**Comment by mnijmeh11** [comment]
I messed up the DNS server and I am waiting for the 24 hours to get it up to see if it is fixed

**Comment by chaneberg** [comment]
This is done. The site html is at statler_site/templates/play-list-page.html and is served through Django.
