### ISSUE TITLE
Git pull and merge photo

### ISSUE THREAD

**Issue by aseebart** [GFUCABAM/statler#30]
![img_20151012_213155275](https://cloud.githubusercontent.com/assets/14076787/10445645/28d56d4e-712a-11e5-8e14-22cf361026d1.jpg)

**Comment by chaneberg** [comment]
![mod4](https://cloud.githubusercontent.com/assets/12008786/10568225/07726086-75ca-11e5-9613-113e4ba5b0c9.png)

**Comment by chaneberg** [comment]
![url routing 0 1](https://cloud.githubusercontent.com/assets/12008786/10568864/a8a3e044-75d2-11e5-9724-22385bd4bfe5.png)
