### ISSUE TITLE
Design Theatre-Initiated API Changes

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#31]
1. On each play's page, we will display only the top few (we discussed two) reviews, selected by review quality and encouraging-ness. Anastasia, this may mean plugging in a second NLP solutions (to gauge quality as well as sentiment)
2. In addition to ranking the top 5 plays overall, we should rank the top two from each night. We'll probably only want the top five to go live at the conclusion of the second night.
3. Though the reviews shouldn't all be viewable publicly, some directors will want a full report of all reviews for their play.

**Comment by areinhardt14** [comment]
Possible quality solutions? 
https://github.com/aarongough/validates_text_content
https://github.com/ooz/Confopy

**Comment by areinhardt14** [comment]
For 1: Should there be a note on the review-posting page that not all reviews will be displayed, since a user posting their review will likely want to see the review on the site to know it was received? What do others think?

**Comment by bencdelaney** [comment]
What if we did this:

![image](https://cloud.githubusercontent.com/assets/3490090/10721810/99686dc2-7b66-11e5-9b9a-a0c52d0cfdc7.png)

If we added a cookie, we could even make a returning user see their review instead of the option to write a new one.

**Comment by areinhardt14** [comment]
I really like this solution. Also, the cookie option would help prevent people from writing multiple reviews for one play.

**Comment by mnijmeh11** [comment]
I will try to get you one...

-----Original Message-----

**Comment by mnijmeh11** [comment]
We can use a PHP to search the database for the username and tell them that you can only write one if they are already in the database for reviews by adding username to the search ...

-----Original Message-----

**Comment by areinhardt14** [comment]
Okay, I added various changes to the spec for 1, but I'm not sure where 2 and 3 will be, implementation-wise. They're included in the spec at a high level, but what will actually be determining/saving them?

**Comment by mnijmeh11** [comment]
look easy to get done...

**Comment by bencdelaney** [comment]
Do we have more work to do here? If so, we should maybe spill this to 0.3, so we can close our milestone tonight.

**Comment by bencdelaney** [comment]
I think we understand this completely enough, and have been handling spec changes as we implement. Let's continue on that track, update spec as we change things, and close this issue.
