### ISSUE TITLE
POST endpoint

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#38]
Write the component that will ingest new user reviews.

**Comment by mnijmeh11** [comment]
Good

**Comment by chaneberg** [comment]
see https://docs.djangoproject.com/en/1.8/intro/tutorial04/

**Comment by chaneberg** [comment]
I can work on this if you want, Anastasia

**Comment by areinhardt14** [comment]
Could you? That would be great... I've been pretty sick since Monday so I haven't gotten to work on it...

**Comment by chaneberg** [comment]
finished in #102
