### ISSUE TITLE
HTML skeleton page for play description

### ISSUE THREAD

**Issue by aseebart** [GFUCABAM/statler#41]

**Comment by mnijmeh11** [comment]
Cool thanks for your website...

**Comment by mnijmeh11** [comment]
Trying to write a python script that will read the reviews and delete them from the database or edits them with ***\* in place of bad words....sorry about that slow inout

**Comment by chaneberg** [comment]
This is done, I'll close it soon if no one objects

**Comment by mnijmeh11** [comment]
no your good
