### ISSUE TITLE
Use Case Diagrams

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#50]
Turn these in to Brent by 10/2

**Comment by mnijmeh11** [comment]
ok...did we alrady do that....
https://drive.google.com/open?id=0B6nZWORC5v7aQ296MERpVnJ6VWs
[Ten Ten Tenreviews.pdf](https://github.com/GFUCABAM/statler/files/24945/Ten.Ten.Tenreviews.pdf)
