### ISSUE TITLE
setting wiki for testing

### ISSUE THREAD

**Issue by mnijmeh11** [GFUCABAM/statler#69]
So I am going to get the wiki updated soon with links andother stuff so that everyone can test their work on the site without having to get one person to test their work....

**Comment by bencdelaney** [comment]
@mnijmeh11, is this complete? If so, it should be closed.

**Comment by mnijmeh11** [comment]
done, we can use the free service with chrome to get free plugsin to test the site with the local server running to get the testing with in broswer...
