### ISSUE TITLE
Post box

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#80]

**Comment by chaneberg** [comment]
Let's change the spec for how posts are sent. Instead of using JSON let's use the regular format for HTML forms, which Django also supports. That should take less work on both the client and server code.

**Comment by chaneberg** [comment]
Take a look at https://docs.djangoproject.com/en/1.8/intro/tutorial04/. It says to put `{% csrf_token %}` in the HTML form to prevent cross-site request forgeries.
