### ISSUE TITLE
Landing page HTML & CSS

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#81]

**Comment by chaneberg** [comment]
@mnijmeh11 and @aseebart will work on this.

**Comment by chaneberg** [comment]
Take a look at play-list-page.html to see how it does the JSON request. The returned JSON includes an `image_url` field, which will be the URL of the play's image.

**Comment by chaneberg** [comment]
[Here's](https://github.com/GFUCABAM/statler/wiki/Web-Page-Storyboard-and-UI-Mockup) the specs for the landing page.

**Comment by mnijmeh11** [comment]
issue closed and completed...
