### ISSUE TITLE
Human review-approval code

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#82]

**Comment by chaneberg** [comment]
@chaneberg will look at admin site option, @B3nD3lan3y will look at custom site option

**Comment by bencdelaney** [comment]
The top review infrastructure is in #108. The admin site workflow we got for free. The web workflow is sitting, partially implemented, in a branch.

**Comment by bencdelaney** [comment]
The most critical parts of this issue are implemented. Let's decide if we add the less critical bits in 1.0

**Comment by mnijmeh11** [comment]
how are we going to prevent unauthorized access and provide access to the reviewer....

**Comment by mnijmeh11** [comment]
Good job
