### ISSUE TITLE
Make site mobile-friendly

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#89]

**Comment by chaneberg** [comment]
Right now bootstrap doesn't seem to be doing anything. This is probably because I put the site in a "page-container" div and it's stopping things from re-sizing. Feel free to remove that div, and make whatever changes are needed to make the site mobile-friendly.

**Comment by mnijmeh11** [comment]
viewport is a simple with using relative in the position of a div to move with window
