### ISSUE TITLE
Get play images from Ten! Ten! Ten!

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#92]

**Comment by mnijmeh11** [comment]
I will try to get pictures from the theater soon...

**Comment by mnijmeh11** [comment]
done

**Comment by mnijmeh11** [comment]
Got first play and posted and emailed to everyone

**Comment by mnijmeh11** [comment]
Dead Right
by Elaine Jarvik

A friend's tedious, grammatically incorrect obituary plunges Penny and Bill into a prickly discussion at the end of a work day. How will the world remember you? Should the world remember you? A touching comedy about discovering what is truly important in life.
![o-reading-newspaper-facebook 2](https://cloud.githubusercontent.com/assets/9537033/11583494/61cc094c-9a0f-11e5-98d6-ae21905433e8.jpg)

**Comment by mnijmeh11** [comment]
Done
